apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/aws/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: agni1984/rc-apartmentsinfo
      context: apartments-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: agni1984/rc-buyandsellinfo
      context: buyandsell-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: agni1984/rc-carpoolinginfo
      context: carpooling-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: agni1984/rc-classifiedsinfo
      context: classifieds-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: agni1984/rc-contactsinfo
      context: contactinfo-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    # - image: agni1984/rc-eventsmgmtinfo
    #   context: eventsmgmt-api
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.js'
    #         dest: .
    - image: agni1984/rc-pollinginfo
      context: polling-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    # - image: agni1984/rc-facilitybookinginfo
    #   context: facilitybooking-api
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.js'
    #         dest: .
    # - image: agni1984/rc-maintenanceinfo
    #   context: maintenance-api
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.js'
    #         dest: .
    - image: agni1984/rc-usersinfo
      context: userinfo-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: agni1984/rc-announcementsinfo
      context: announcements-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    # - image: agni1984/rc-visitormgmtinfo
    #   context: visitormgmt-api
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.js'
    #         dest: .
    - image: agni1984/rc-paymentsinfo
      context: payments-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
