apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc-carpoolinginfo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rc-carpoolinginfo
  template:
    metadata:
      labels:
        app: rc-carpoolinginfo
    spec:
      containers:
        - name: rc-carpoolinginfo
          image: agni1984/rc-carpoolinginfo:latest
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://admin:admin@residentsconnect-cluste.r0t44.mongodb.net/carpoolinginfo?retryWrites=true&w=majority'
---
apiVersion: v1
kind: Service
metadata:
  name: rc-carpoolinginfo-srv
spec:
  type: ClusterIP
  selector:
    app: rc-carpoolinginfo
  ports:
    - name: rc-carpoolinginfo
      port: 4006
      targetPort: 4006
