apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc-eventsmgmtinfo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rc-eventsmgmtinfo
  template:
    metadata:
      labels:
        app: rc-eventsmgmtinfo
    spec:
      containers:
        - name: rc-eventsmgmtinfo
          image: agni1984/rc-eventsmgmtinfo:latest
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://admin:admin@residentsconnect-cluste.r0t44.mongodb.net/eventmgmtinfo?retryWrites=true&w=majority'
---
apiVersion: v1
kind: Service
metadata:
  name: rc-eventsmgmtinfo-srv
spec:
  type: ClusterIP
  selector:
    app: rc-eventsmgmtinfo
  ports:
    - name: rc-eventsmgmtinfo
      port: 4003
      targetPort: 4003
