apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc-visitormgmtinfo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rc-visitormgmtinfo
  template:
    metadata:
      labels:
        app: rc-visitormgmtinfo
    spec:
      containers:
        - name: rc-visitormgmtinfo
          image: agni1984/rc-visitormgmtinfo:latest
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://admin:admin@residentsconnect-cluste.r0t44.mongodb.net/visitorsinfo?retryWrites=true&w=majority'
---
apiVersion: v1
kind: Service
metadata:
  name: rc-visitormgmtinfo-srv
spec:
  type: ClusterIP
  selector:
    app: rc-visitormgmtinfo
  ports:
    - name: rc-visitormgmtinfo
      port: 4011
      targetPort: 4011